---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: todos-env
  namespace: todos
spec:
  encryptedData:
    DATABASE_URL: AgAf2LlNJq5Pv/fYOEOOLJ/HjH8wURhMM8iF3JAwbCyQKQXlVEFeG5kudq6YTvvfJ62gOZ0Kb0tBc0/oUSMLO4fT/39yETPwsXN2nCJ5QoLULbBcUSRb4iz+aHcs9j/nDtzwZipLbuQ4Bjn5kj6nqpFAF/dSO5OP6i/STFEU5m0UvWyYpbQ2v43viVatOal5GZk1Nt5zrXad2tVveyUwDD3osWRxR2AqwZeAbBDTV9Sz86V8BJsnpUtPqrzpTIHQNtIWcmZ3txV4xTLCp+hKn59JvgK77rAEdc2MO2/4rSe8wAyRHr/i5LI2jdmwrODHCN+5zbiomZLPIUqlcsl2l5x7/A1m5Q3TSAhnpnOqJwpWagywyI3XpNr+Ir18ydo7xtBxj7uY9OvNZ/YS4s4mS3ws1LLbKIMKKFcX53tGqsX2HB0bh3V8X4bJ8RbDjGZZd/DEOs5FcaUXRU/wyGWtjFbyU68z82k2Th+fAbocYo3+Dt8Xl5LgaBgeiYbJvahaP1W+hPQbZ1QUTFoi8RzxJIhbwsIVrdDzTlMsvK3TM6P5pgQkTcOkt2RqHwI7Sf3ebz8Ae0VyMxjuZhd60c2lqzKgiOLOA9XtqUKpM3WZsWUHmWAx5HVcMOkNLyUbNCiaT4HLlJSjpDnX2wd1VdAnRq7GX2pFAadfVf/913OInhCD+jTm0Uc9DdK+4or//nRzy7NMn4ZLn56mFVvtLEcqDroyfoKowbbM9U80zOdTX8p7tYsP/tvRbLiZ2u/GZlg5wHcatdG8NNcB5hKj0xGfLJbvDIyqPaNzeDId9k+ift+qBfcyrZ/wQfLpnk5OrBMAx4SpldNUHZFWEwhzPFsTD9ejndVodViRtjU8KkSmaFA=
  template:
    metadata:
      name: todos-env
      namespace: todos
