---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: todos-env
  namespace: juntos
spec:
  encryptedData:
    DATABASE_URL: AgAAkHMuK8VyVPE9x8iiQkUCcU8LEkRgEFsSdeNmsLdYiKCcBtmXWppE8DloufYZeayBBL8yaJfWUulQZ9ZVNquWNU3U9/izbiLq5YhADPilLRXWBqSAxDfzO/OH/leB9ZC27vb2lxrpTJLbrTUVn60NUz/oKM7lAV3F5f3XMek7tI7eASDwHKPXM4hw8q+yRKwaQpyWGpLNj2pZ9inBsyeI0hbiN9Rml9ta8StHaspBUM7sT0W2yt0jEbaf/s/6+wNfzqAuRUKR5n7Zar4/JAbmGsB4MHQXBCzH21TJycBSCCZ7uImjqE9wPZx6hvWnAdeJEnPYMcIS5w1A2CaRTTClDqIUCMrw3c4mwa3y1L8+4+ecT/5p0PtwvTMpYhI8PsdAOctPnyJOM+afM4hx1x5QK65FQ/MXLgYiU0zwfa65MPyZYvRap9X4/wIyhNkBmd/LlaYAk02BLPBWckUoN9KoHgkIUAXeuJzW0sZ0GbFKcUbPB/F/Y/Ajm68KnMLdcsAivbPFMga/QPkTWFn/xmixyry7GAK1EjHXJZw/ZtRxwu5LfQ8PVFHoFdUOVPtW6DAP/YsD5BfPz4RecLrSlv4qBLEM+ZMfLQhMkQ8dWqOIGJCyu7ZLOrjx63QU9CGNqefwgaw4iPF0uRUbazdMRUNNHTyBfKq6+VbZ3DyA9HAmb52lAvkYuWvdrdvMgwm6IFfZyhw+qdtbygBsGnWvO45fEOopZ8bcqX0cHRfFRQXpiD/MdWPVW03w+QGO2zfe/oXX1arow6Xsm0ltYm425Q+tRF8t7l45
  template:
    metadata:
      name: todos-env
      namespace: juntos
