---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: recipes-env
  namespace: juntos
spec:
  encryptedData:
    DATABASE_URL: AgCzSzOPZqBACHumAkicdZ8owmeo2x/RyZTSwJ9PSlydSUoD6YAraf9Noj0yj13J42wT+svFwVR7UzMjFObKT6mEG/rGmgglKQJClQ872RvTlCT4GNFA8QxL4qvXFkvwWJTyFo5SgZ5SSir9eMhMRfekNJdBqWx7okehViHSZ2HGzVevmZRCYjR7zCeOgE8dWXmhsbHC6OWrZQxK0szdSDkbiwV4qu+7hSWFYcpYopdc7mpSFn+k1rbZuaWQ64dd3FH5Pv6GBx58SehwXnWCVC9JnnzffGdL6ne9Xd3DLPlhvt2tcPLTZWxvgYMyNe2EsAFYWQQoc8IVKlR4Grhn/9W3m6jpp5QRyH2f/V3D7PCMaObvNZk+1EjV7TIisgFE+7e9fCe6uYD8AP4iroDsRKjMC1FIf4j6LXILh/WVy/I7VxjOHBzTA5EBrNGX3F23JY2z30qT8/4zVTEuyCja3MDT/mLQmsYixNglk8oqTe75sQI1UnlvPnBzsq+xfgXHjCTsiwoDyT4JRj1TsY9AV7NviQzqH23sdF6hkCxDaypOeN4qSnU5QQjccnbkz+GWqyRN9IDTsNUkbMbPidcP6qdLI/WR788fp+WGwauMp1L1cfLx3aW4Z1mAR6QIKzM84fLMvHarxxHSgUODkLI/gMm6eVawB7V7oWWb6kKy1NS7hx9H3yhcZYbtD5KCT6VZmZpIvtj9zPYeUA7Fm626OcBhFbPRoXs0PTn4xN0EpNrmblneYWU+OSaeYqwG6wFTh3oIvxaSq10Gba5uCnOfYpF2r7Hscw6b1d0=
    PORT: AgCqE8OhKEEbmeQUENPGB0f+AzTXgeffn39GOIXmmSNqwZiXREte5QQRg4ldDt81VgdA9//eNOGMg02eq9iwylTS6GnQTPfJdz3WU56ZrKsWFnK4g844q+1nlMQnLh6XWyXLzDazFxMsrKQJTqlX8/m0ZInOxHwIX0XGVxk5ZwmbZpX6DX8TpTIgcVT0XHqHyYXYXTtMARQpJeiK3SJ+eInNcEU6typpi14JvIJ/AFmLE3I4JDArNfzWGWW0fPHovoMKPbTygtUlJ7VFrri4rRbbJlxrUUurQxqLbe+bORWufoAyzS79F59qL80K/LB/y7a4lp27Hu1yqHHQPgKfkyG6ArAMLGwoRhPXIt8Te+ONLbWHMIjJADslf7Ou7y6it/xt8MWB8ytK9ICgPkKKnUTA4Kd8JEurY3sDjivoIBnsXVVC8zvADz11ciCMO3epEngqYefJROgC/Ce0OKEVSfNx30VTKr/vAex/UmdFSGfyIedRh8/TzJydpeG4btryEXOMeh07M3zqquNIp7XREPNpmTxSX18OGJtqaTSn22Eyc2+anpZHYUWqwZHE6hmDwnHGSVz9C0MzRspZbdI/yMwy3c3ZMBAAXVMABGz44Rz/VQiNHwHb/mcyF8C6RIt2/xJ1aIERG1AxXoDzFi7aqwqGOZif/UAdk7EofUoiRYwClIXX3utaAIsM+G28xdPQw9HHJ6t+
  template:
    metadata:
      name: recipes-env
      namespace: juntos
