---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: recipes-env
  namespace: juntos
spec:
  encryptedData:
    DATABASE_URL: AgABPTXOI33SQqLe3hncqECpcuRPycg3hp80IaLLLtXYvLOiRxDEknylydcDl0y+oMlD1HtVgTSF8/KNtERiLms+u7W4+fhoVOR+n1vw8UjgQMmG+86kSxuiFBd7wgz9YsLH3daZ/bwWoPhmOEgwE4QhScQQnSZK+a7u025QAnSEZzY38h2OazKHS/UoMAenUmZ+MAMHoorPWqTxoqLsnfUs1S6IIDlLZlMYwJ4N6633Uv5hucNYSQoPh1ynfmAzUwNBP0bdBL463ws3afBTqfaDLRTTxPWR6tdo33dx0FUpJmOOZkDhA6JN1sk7FEE30Mj51jxN7OKQM1kXUdSzPLm21yllZ/97M6CJw9oVs6SJhFioMmW8wcJfgtv4Ymrr9rSaO9wbhyYyyUM+UB+qRmi8FNjxyN6lgV4txrgRJroYdwzD7zAwuyfTM7y6bnljG17rJp8qMnWMDBPURyVB1Ts/C8/nalkA06h8+QseN+FV8JFKI95a67ykdF161lpQpNt2teeXaX9Qteaae4L7I0vP40YcrvzldJ/AHDLfBtzhUSvHpL1Bg0/ZKuYFsxxxhPs/wgJv+hiMb88QMCc6enpO+YxEYELg+MmZ4AqTA89/l+a3Ge5jTqCFOq4bR9RMB1FLao1dxLuo5oZJHIw9FWT6uZqAL8sxKDmBV3et9g18fdrmu07jmE5iNPR4RwVzeqL2ygJ9HAhC7bSSBmHeXcAEKAHAmNhkETH0fpIdv9nwJRSkZ1c6M3WAwqdST+wWuAHKfEnDmrJWj36q/+F2IMyY7sSoTgIhh3E=
  template:
    metadata:
      name: recipes-env
      namespace: juntos
