---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCD0h0wmAjPzqAxkpWI+DM0og2MHn3dLTs+TWURFhP9D8ClVL8yL8Abx2iNCVyxd0krj5S2e4/rVxHmE5GSPR/wz70qMGsZM6t9iw3rvedlmPwMrPBjFBP9AYrYfBYA0xkV29oG5D2Gn6pZJyXAZrIJxvxmiUZ51Jl50hUGE3FncDSVatFx+sb/V3LkkQBWwQd7FizNIv3Xg2nb22mWkNWu3TT9mfal4XBn7G605i7Cz0u8lrh/VkpJ65QRZbxwgZnJ/aERbs/d5bFV4DJ0ga0jmwlzfxV3qSgLFKYkvIMQvxqUCTLwZVP7pfM3uP038WZh5hFefVoEydUpvOMfGKpfrImaBN1GvK1OCmAbab3p0Oim3Lx7M6P8QEl+yAjBuEUxMhaP4MJOJboGLqkO7OuB9r+EJs7OWNT1++sJtsiLM4LMJjKzOC4rCukNjYHT+D5NWysonJHRA5kb9UGTUFk354Ucbm0I+JeeUDZjt9iiwq5D+hrxZQuHOPugwX11bZzhVU1Ix1jhmYhjld4iDjNacjYlTFhaOEui7fIxmreo2LTYNLqzI7IPMXYgeSsfvKiIZreJct0ic7P48bbOxEa9GJ8D07P5cNiRbsc6b+wTblwVj64FbRKpmphvyi7dO0XOE3AgdWimOYmWHtYPkjGd1f45q+TzK+dh2XCyWNCDwQ06RGCawyKVVnSCChm3UIuVAhg9Jo2bAPgD1shriY8XZDiqMfqidXRItvqfUNYEbG+bpU0whI/MEvWIzKiCSkdmwFPWlg==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
