apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: finances
  namespace: finances
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - host: finances.home
    http:
        paths:
          - path: /finances(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: finances
                port:
                  number: 80
