---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-token
  namespace: networking
spec:
  encryptedData:
    TUNNEL_TOKEN: AgB3qmAWyIz620f8/9kDFfakGbyab9Zf4w4LvuUrxQZXJd99eOXbYm3AxCu1CUUmoE+uwPi+NHiyf5LmlzyKhg7J/BvjTfVOI53MmHNgawgr57U/JV8VPWq2K3nJeWbOKHR2bYgCx/xDeJ42sovMZWtWKQEv0fbLzBUPtS40NlgotlbSlydlyKLkHzaAFVRz801DrPaXhoCKR3uK+YMP7GHZcUANTaxhPqBVeK+clA9BIocCiWPLoSq8+ZeDtyWu4O0aObXC/7SeiMEEZWW1Lc2gm7TeS3d3FKFAwtPkYCbxuDe8riR82mzyXAxGD6AnUc0bASe/9cWuIGWP4wVfMCmia4W+sQv3xFq+T7k1/mcRMuXHiZsOambHqQ306OudQdeXKKF5NtQJO3Eb3hDk+wLAfUgdZsNfP8NDIEX3Ze1D/Opn5nfwRSjIxEE4xm/3zJLHdLPJsc6Ej7PRo5UN6AoXdx5zLAG5E9ggmur2gZIWaVgpLXGufq0WfAMMESxMITfcOOvVl3L9RjXZyueKRt8Y44Muynq+c7Wl/KpYpgpBF583gZyaN+sjaVVA9wFJKQ8JULQPpZP7qj/vJfD/PQafKNzQB4F2f0iZ7EsVy8b+6q3wZoy6bAjBu+UH0vbVFJyMgLWUg1rtlwEe607UsW4WdI0X+JJM2YxF4ms9XR0wRJOxO5dBBE5CxvwC6tg4Muo28Nug1FfVkyW31rdGjG8CIEEU1oNJ2gyqX7Y0H3jckjkFRBIJ3DyAcZ/8NwoPEuDle1ckzNNVW2bsh4dbqY1jfFLbvQbFIqmnjkkwhwuXYhO7l6D9iGfXcQ4XfuGxtP351Jrr0iZZuv2fuRd5T49cD29uQXyZc+LFEB4ACQtNox5qdZlROmbDokAkUG3CvVeQVr+djzSqLy7qnxn0leTbhAZffAuL7+7ii4QbnR3vUGqEAnQJlBjz
  template:
    metadata:
      name: cloudflared-token
      namespace: networking
