---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-token
  namespace: networking
spec:
  encryptedData:
    TUNNEL_TOKEN: AgAwUcRzdYBwfdc+WGsmWd+2BfPwDDNesdcnOLZVmsNgdppptBdb3AUxpAmnsoVo8Tl2T02SRmTvrKx1UgvESPu7ttwuJFW9gOBprcH8c6BgW8WIRiQ+CN2Aex1xzdWdwMQOI2h8e+IvUi9IUDv2TkZw5yDtrLFmKOpziGQkGBmkqWyK5KfROTcbZT7wZ5kYc1A22/FLZ/hUaUUMAjqAu7mFha+giTLE/cuP9qj0TystOTwbq1ZiXrW5Dyi9U/zM6p1h/zWGewIMUmfrJsS1vCAuJGBLAwRdCWYuDQqV6x7i6QfDSOUmJHr0fb5cGLHWsLD+r530G3I1eszCmM2WUuwn2Mz6S/cL6kDF2QeTI6xmeVA91XhWwqfIHvi8Ajrg/mnlGB4gB0Gp9d0AUgKdaJPFLYjBlcvmIK75kEw/3+E8Z6N1VAAFFr0/7/4UEXHUhTcyhc88GH7tgJZopAZG7ppcZklqZOhSY30AE9Po6tvuRZbQcr27cUU3Hhsi0G5y23ithgQvkKVD7zTw77kDgISJjpoLE73u9cL6KqOFTjrmkSyvopmw45k1iasV4yEoiaf5RkviYoglWXHLAmH9Dx3OrazeNc8yrhCvKd/bWBe4MlIuj7V++HN1RFyhkdL9x+3GH18lc2WrmYgb0IQggZDV6j5csfl6f426BFIBFwiKfZdVbfI6FwXwDdsLpiPmJgUp56rmP4/rU8FV+z60f4uJzOqNg/23e3A5r+dNBDkd7tFR11EFyRWaazSa2DaRKXvdUXeYHgnEVkATohq7sn0hAzXKLkkFGKZH8vPrSGdOoKQ9DrA7ljhPcW5g4MBXfWV9oTEQcnx0oVlq4lpdqrrHOnPiv7cnSDi3LFlf0iaWpEkqG/Ok47BpTG8IRKWIKJ0e62dqLFTkKsgKChg/YqdY1ENeO3XBCPT+jFfyAqGK7rrwL1G3IwWR
  template:
    metadata:
      name: cloudflared-token
      namespace: networking
    type: Opaque
